author: DerFlash
database: false
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: de.derflash.plugins.cntransporteraddon.CNTransporterAddon
name: CNTransporterAddon
startup: postworld
url: http://www.cube-nation.de/
version: '1.0'

depend:
  - WorldGuard
  - Transporter

commands:
  tra:
    description: Restart ...
